### PR TITLE
index.js: fix template path: it should be readme.md in lowercase

### PR DESCRIPTION
**Pull request by hsanjuan**
This causes a silent failure in case-sensitive filesystems as the
generator cannot find the template file.

### CODE REVIEW

**Comment by RichardLitt** [comment]
Should be in caps. Can we fix it the other way?

**Comment by RichardLitt** [comment]
See first requirement. https://github.com/RichardLitt/standard-readme/blob/master/spec.md

**Comment by hsanjuan** [comment]
indeed

**Comment by RichardLitt** [comment]
Merged and patched and published.

**Comment by hsanjuan** [comment]
ah i was fixing the tests too

**Comment by RichardLitt** [comment]
Ah, sorry! Another PR?

**Comment by RichardLitt** [comment]
That can close #4.

**Pull request merged**
